export const navigationComponentNames = {
    FeedStack: "FeedStack",
    ActivitiesStack: "ActivitiesStack",
    ChatStack: "ChatStack",
    ProfileStack: "ProfileStack",
    ActiviyTabNavigator: "ActiviyTabNavigator",
    ChatListScreen: "ChatListScreen",
    FeedContainer: "FeedContainer",
    ProfileTab: "ProfileTab",
    ProfileActivityContainer: "ProfileActivityContainer",
    ProfileContainer: "ProfileContainer",
    ProfileFotoGalery: "ProfileFotoGalery",
    ActivityList: "ActivityListView",
    ActivityMap: "ActivityMapView",
    FriendListContainer: "FriendListContainer",
};
